config/routes.rb
Slog::Application.routes.draw do
  resources :blogs

end

app/models/blog.rb
class Blog < ActiveRecord::Base

#validates_attachment_presence :photo
#validates_attachment_size :photo, 
#	:less_than => 5.megabytes
#validates_attachment_content_type :photo, 
#	:content_type => {"image.jpeg", "image.jpg", "image.png"}

has_attached_file :photo,
:styles => {
  :thumb => "100x100#",
  :small => "150x150>",
  :medium => "300x300>",
  :large => "600x600>"}

include Tire::Model::Search
include Tire::Model::Callbacks

#searchable do
#  text :name, :title, :article, :created_at
#  string :name, :title, :article
#  time :created_at
#end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  # GET /blogs
  # GET /blogs.json
  def index
    if params[:query].present?
      @blogs = Blog.search(params[:query], load: true)
    else
      @blogs = Blog.all
  end
#    @search = Blog.search do
#      fulltext params[:search]
#      order_by :name, :desc
#      paginate :page => params[:page], :per_page => 5
#    end
#    @blogs = @search.results

#    @blogs = Blog.paginate(:page => params[:page],
#                           :per_page => 5,
#                           :order => "created_at DESC")
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @blogs }
    end
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @blog = Blog.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @blog }
    end
  end

  # GET /blogs/new
  # GET /blogs/new.json
  def new
    @blog = Blog.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @blog }
    end
  end

  # GET /blogs/1/edit
  def edit
    @blog = Blog.find(params[:id])
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(params[:blog])

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render json: @blog, status: :created, location: @blog }
      else
        format.html { render action: "new" }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /blogs/1
  # PUT /blogs/1.json
  def update
    @blog = Blog.find(params[:id])

    respond_to do |format|
      if @blog.update_attributes(params[:blog])
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_datetime(time)
  h(time.strftime("%A, %B, %d, %Y %I:%M%p"))
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.haml
= form_for(@blog) do |f|
  - if @blog.errors.any?
    #error_explanation
      %h2
        = pluralize(@blog.errors.count, "error")
        prohibited this blog from being saved:
      %ul
        - @blog.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :title
    %br/
    = f.text_field :title
  .field
    = f.label :photo
    %br/
    = f.file_field :photo
  .field
    = f.label :article
    %br/
    = f.text_area :article
  .actions
    = f.submit

app/views/blogs/_search.html.haml
#search
  = form_tag blogs_path, :method => :get do
    %p
      = text_field_tag :query, params[:query]
      = submit_tag "Search", :name => nil

app/views/blogs/edit.html.haml
%h1 Editing blog
= render 'form'
= link_to 'Show', @blog
|
\#{link_to 'Back', blogs_path}

app/views/blogs/index.html.haml
= link_to 'New Blog', new_blog_path
%table
  - @blogs.each do |blog|
    %tr
      %td#name= blog.name
      %td#title= blog.title
      %td#date= render_datetime(blog.created_at)
      %td#photo= image_tag blog.photo.url(:large)
      %td#article= blog.article
      %td.links= link_to 'Show', blog
      %td.links= link_to 'Edit', edit_blog_path(blog)
      %td.links= link_to 'Destroy', blog, confirm: 'Are you sure?', method: :delete
%br/
/= will_paginate @blogs

app/views/blogs/new.html.haml
%h1 New blog

= render 'form'

= link_to 'Back', blogs_path

app/views/blogs/show.html.haml
%p#notice= notice
%p
  %b Name:
  = @blog.name
%p
  %b Title:
  = @blog.title
%p
  %b Photo:
  = image_tag @blog.photo.url{:small}
%p
  %b Article:
  = @blog.article
= link_to 'Edit', edit_blog_path(@blog)
|
\#{link_to 'Back', blogs_path}

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Slog
    = stylesheet_link_tag     "application"
    #banner=image_tag("alter.png")
    = render 'search'
    = javascript_include_tag  "application"
    = csrf_meta_tags
  %body
    = yield